version: '2'
services:
  php:
    container_name: 'crudyii2_alejandro'
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
        - mysql
  mysql:
    container_name: 'prueba_emoac_db'
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    command: --sql_mode="TRADITIONAL"
    environment:
      MYSQL_DATABASE: 'crudalejandro'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
  phpmyadmin:
    container_name: 'prueba_emoac_myadmin'
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - mysql
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
